import Head from "next/head";

import React from "react";
import { Button } from "../components/Button.component";
import { Navigation } from "../components/Navigation.component";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Benjamin Schachter (benschac)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <section>Hello</section>

        <Button
          // Todo: fix me
          // @ts-expect-error
          onClick={() => alert("hi")}
        >
          Hello
        </Button>
      </main>{" "}
    </div>
  );
};

export default Home;
